-- Insert pricing plans into the existing plans table
INSERT INTO plans (
    name,
    display_name,
    description,
    plan_type,
    price_monthly,
    price_yearly,
    monthly_audio_hours_limit,
    max_documents_per_session,
    max_file_size_mb,
    max_sessions_per_month,
    max_organization_members,
    has_real_time_guidance,
    has_advanced_summaries,
    has_export_options,
    has_email_summaries,
    has_api_access,
    has_custom_templates,
    has_priority_support,
    has_analytics_dashboard,
    has_team_collaboration,
    ai_model_access,
    max_guidance_requests_per_session,
    summary_generation_priority,
    is_active,
    is_featured,
    sort_order
) VALUES
-- Individual Free Plan
(
    'individual_free',
    'Starter',
    'Perfect for trying out liveprompt.ai',
    'individual',
    0,
    0,
    1, -- 1 hour per month
    5,
    10,
    10,
    NULL,
    true,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    '["gpt-4o-mini"]'::jsonb,
    20,
    3,
    true,
    false,
    1
),
-- Individual Pro Plan
(
    'individual_pro',
    'Professional',
    'For professionals who need more power',
    'individual',
    29,
    290,
    NULL, -- unlimited
    20,
    50,
    NULL, -- unlimited
    NULL,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    false,
    '["gpt-4o-mini", "gpt-4o"]'::jsonb,
    100,
    1,
    true,
    true,
    2
),
-- Organization Starter Plan
(
    'org_starter',
    'Team',
    'Great for small teams',
    'organization',
    79,
    790,
    NULL, -- unlimited
    50,
    100,
    NULL, -- unlimited
    10,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    '["gpt-4o-mini", "gpt-4o"]'::jsonb,
    200,
    1,
    true,
    false,
    3
),
-- Organization Enterprise Plan
(
    'org_enterprise',
    'Enterprise',
    'Custom solutions for large organizations',
    'organization',
    NULL, -- custom pricing
    NULL, -- custom pricing
    NULL, -- unlimited
    NULL, -- unlimited
    NULL, -- unlimited
    NULL, -- unlimited
    NULL, -- unlimited
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    '["gpt-4o-mini", "gpt-4o", "claude-3-opus", "custom"]'::jsonb,
    NULL, -- unlimited
    1,
    true,
    false,
    4
)
ON CONFLICT (name) DO UPDATE SET
    display_name = EXCLUDED.display_name,
    description = EXCLUDED.description,
    plan_type = EXCLUDED.plan_type,
    price_monthly = EXCLUDED.price_monthly,
    price_yearly = EXCLUDED.price_yearly,
    monthly_audio_hours_limit = EXCLUDED.monthly_audio_hours_limit,
    max_documents_per_session = EXCLUDED.max_documents_per_session,
    max_file_size_mb = EXCLUDED.max_file_size_mb,
    max_sessions_per_month = EXCLUDED.max_sessions_per_month,
    max_organization_members = EXCLUDED.max_organization_members,
    has_real_time_guidance = EXCLUDED.has_real_time_guidance,
    has_advanced_summaries = EXCLUDED.has_advanced_summaries,
    has_export_options = EXCLUDED.has_export_options,
    has_email_summaries = EXCLUDED.has_email_summaries,
    has_api_access = EXCLUDED.has_api_access,
    has_custom_templates = EXCLUDED.has_custom_templates,
    has_priority_support = EXCLUDED.has_priority_support,
    has_analytics_dashboard = EXCLUDED.has_analytics_dashboard,
    has_team_collaboration = EXCLUDED.has_team_collaboration,
    ai_model_access = EXCLUDED.ai_model_access,
    max_guidance_requests_per_session = EXCLUDED.max_guidance_requests_per_session,
    summary_generation_priority = EXCLUDED.summary_generation_priority,
    is_active = EXCLUDED.is_active,
    is_featured = EXCLUDED.is_featured,
    sort_order = EXCLUDED.sort_order,
    updated_at = CURRENT_TIMESTAMP;